
name: "Runnig Python"
author: "Me"

runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"

inputs:
  issue-name: 
    required: true
    default: "issue without a name"

  
